name: Update Webflow CMS

on:
  push:
    branches:
      - main
    paths:
      - "*.html"

jobs:
  update-webflow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get changed HTML file
        id: changed
        run: |
          FILE=$(git diff --name-only HEAD~1 HEAD | grep '\.html$' | head -1)

          if [ -z "$FILE" ]; then
            echo "No HTML file changed."
            exit 0
          fi

          echo "file=$FILE" >> $GITHUB_OUTPUT

      - name: Generate URL
        id: page
        run: |
          FILE="${{ steps.changed.outputs.file }}"
          NAME=$(basename "$FILE" .html)

          URL="https://neha-coditation.github.io/Case-Studies/$FILE"

          echo "name=$NAME" >> $GITHUB_OUTPUT
          echo "slug=$NAME" >> $GITHUB_OUTPUT
          echo "url=$URL" >> $GITHUB_OUTPUT

      - name: Create Webflow CMS Item
        run: |
          curl -X POST \
          "https://api.webflow.com/v2/collections/69e88bdf798339812888e292/items/live" \
          -H "Authorization: Bearer ${{ secrets.WEBFLOW_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "isArchived": false,
            "isDraft": false,
            "fieldData": {
              "name": "${{ steps.page.outputs.name }}",
              "slug": "${{ steps.page.outputs.slug }}",
              "html-url": "${{ steps.page.outputs.url }}"
            }
          }'
